n = input('Digite algo: ')
print('O tipo primitivo é: ', type(n))
#print(n.isidentifier())
print('É alfanumérico?', n.isalnum())
print('É Alfabetico?',n.isalpha())
#print(n.isascii())
print('É decimal?', n.isdecimal())
print('É um dígito?', n.isdigit())
print('Está em minúsculo?', n.islower())
print('É um número?', n.isnumeric())
#print(n.isprintable())
print('É um espaço?', n.isspace())
print('Está capitalizada?', n.istitle())
print('Está em maiúsculo?', n.isupper())
